package robocup.model.enums;

public enum Command {
	HALT,
	STOP,
	NORMAL_START,
	FORCE_START,
	PREPARE_KICKOFF_YELLOW,
	PREPARE_KICKOFF_BLUE,
	PREPARE_PENALTY_YELLOW,
	PREPARE_PENALTY_BLUE,
	DIRECT_FREE_YELLOW,
	DIRECT_FREE_BLUE,
	INDIRECT_FREE_YELLOW,
	INDIRECT_FREE_BLUE,
	TIMEOUT_YELLOW,
	TIMEOUT_BLUE,
	GOAL_YELLOW,
	GOAL_BLUE;
}
