package robocup.model.enums;

public enum Event {
	BALL_ENEMY_CHANGEOWNER,
	BALL_ALLY_CHANGEOWNER,
	BALL_ALLY_CAPTURE,
	BALL_ENEMY_CAPTURE,
	BALL_MOVESPAST_NORTHSOUTH,
	BALL_MOVESPAST_MIDLINE,
	REFEREE_NEWCOMMAND,
	ROBOT_ENEMY_ATTACKCOUNT_CHANGE;
}
