package robocup.model.enums;
/**
 * An enumeration that describes possible roles of Robots
 * Examples are: Keeper, Defender, Attacker and Blocker.
 */
public enum FieldZone {
	WEST_RIGHT_CORNER, WEST_RIGHT_SECOND_POST, WEST_CENTER, WEST_LEFT_SECOND_POST, WEST_LEFT_CORNER, WEST_RIGHT_FRONT, WEST_MIDDLE, WEST_LEFT_FRONT, WEST_GOAL_RIGHT, WEST_GOAL_LEFT,
	EAST_RIGHT_CORNER, EAST_RIGHT_SECOND_POST, EAST_CENTER, EAST_LEFT_SECOND_POST, EAST_LEFT_CORNER, EAST_RIGHT_FRONT, EAST_MIDDLE, EAST_LEFT_FRONT, EAST_GOAL_RIGHT, EAST_GOAL_LEFT;
}